variables:
  IMAGE: bankexlabs/$CI_PROJECT_NAME:release

stages:
  - setup
  - build
  - release
  - deploy-stage
  - deploy-prod

cache:
  paths:
    - node_modules/

setup:
  image: node:alpine
  stage: setup
  script:
    - apk add --update git
    - apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python
    - npm install --quiet node-gyp -g
    - npm install
    - npm rebuild bcrypt --build-from-source
    - npm rebuild node-sass

build:
  image: node:alpine
  stage: build
  script:
    - npm run build:aot:prod
  artifacts:
    paths:
      - dist
    expire_in: 12h

release:
  image: docker:latest
  stage: release
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
  script:
    - docker build -f docker/Dockerfile -t ${IMAGE} .
    - docker push ${IMAGE}

deploy-stage:
  stage: deploy-stage
  image: tmaier/docker-compose
  variables:
    DOCKER_HOST: "tcp://charity-staging-do.bankex.team:2376"
    DOCKER_TLS_VERIFY: "1"
    SERVERNAME: donatorscab.staging.bankex.team
    EMAIL: "om@bankexfoundation.org"
    DOCKER_CERT_PATH: "/certs"
  before_script:
    - mkdir -p $DOCKER_CERT_PATH
    - echo "$DO_DOCKER_CA_STAGE" > $DOCKER_CERT_PATH/ca.pem
    - echo "$DO_DOCKER_CERT_STAGE" > $DOCKER_CERT_PATH/cert.pem
    - echo "$DO_DOCKER_KEY_STAGE" > $DOCKER_CERT_PATH/key.pem
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - echo "IMAGE=$IMAGE" > .env ; echo "VIRTUAL_HOST=$SERVERNAME" >> .env ; echo "LETSENCRYPT_HOST=$SERVERNAME" >> .env; echo "LETSENCRYPT_EMAIL=$EMAIL" >> .env
  script:
    - docker-compose -f docker/docker-compose.yml down
    - docker rmi $IMAGE || echo "image not exist"
    - docker pull $IMAGE
    - docker-compose -f docker/docker-compose.yml up -d
  environment:
    name: staging
    url: https://donatorscab.staging.bankex.team
  when: manual

deploy-prod:
  stage: deploy-prod
  image: tmaier/docker-compose
  variables:
    DOCKER_HOST: "tcp://charity-prod-do.bankex.team:2376"
    DOCKER_TLS_VERIFY: "1"
    SERVERNAME: donatorscab.bankex.team
    EMAIL: "om@bankexfoundation.org"
    DOCKER_CERT_PATH: "/certs"
  before_script:
    - mkdir -p $DOCKER_CERT_PATH
    - echo "$DO_DOCKER_CA_PROD" > $DOCKER_CERT_PATH/ca.pem
    - echo "$DO_DOCKER_CERT_PROD" > $DOCKER_CERT_PATH/cert.pem
    - echo "$DO_DOCKER_KEY_PROD" > $DOCKER_CERT_PATH/key.pem
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - echo "IMAGE=$IMAGE" > .env ; echo "VIRTUAL_HOST=$SERVERNAME" >> .env ; echo "LETSENCRYPT_HOST=$SERVERNAME" >> .env; echo "LETSENCRYPT_EMAIL=$EMAIL" >> .env
  script:
    - docker-compose -f docker/docker-compose.yml down
    - docker rmi $IMAGE || echo "image not exist"
    - docker pull $IMAGE
    - docker-compose -f docker/docker-compose.yml up -d
  environment:
    name: prod
    url: https://donatorscab.bankex.team
  when: manual
  only:
    - production
